#!/usr/bin/env node

/**
 * sync-catalog.js
 * Scans data/materials/*.json, updates data/materials/manifest.json and bundles into data/catalog.js.
 * Usage: node scripts/sync-catalog.js
 */

const fs = require('fs');
const path = require('path');

const ROOT_DIR = path.resolve(__dirname, '..');
const MATERIALS_DIR = path.join(ROOT_DIR, 'data', 'materials');
const MANIFEST_PATH = path.join(MATERIALS_DIR, 'manifest.json');
const CATALOG_BUNDLE_PATH = path.join(ROOT_DIR, 'data', 'catalog.js');

function syncCatalog() {
  if (!fs.existsSync(MATERIALS_DIR)) {
    console.error(`Error: Materials directory not found: ${MATERIALS_DIR}`);
    process.exit(1);
  }

  const files = fs.readdirSync(MATERIALS_DIR)
    .filter(f => f.endsWith('.json') && f !== 'manifest.json')
    .sort();

  const materials = [];
  const manifestList = [];

  for (const file of files) {
    const filePath = path.join(MATERIALS_DIR, file);
    try {
      const content = fs.readFileSync(filePath, 'utf-8');
      const item = JSON.parse(content);

      if (!item.id || !item.chinese || !item.english) {
        console.warn(`[WARN] Skipping ${file}: Missing required fields ('id', 'chinese', or 'english')`);
        continue;
      }

      materials.push(item);
      manifestList.push(file);
    } catch (err) {
      console.error(`[ERROR] Failed to parse ${file}:`, err.message);
    }
  }

  // Update manifest.json
  fs.writeFileSync(MANIFEST_PATH, JSON.stringify(manifestList, null, 2) + '\n', 'utf-8');
  console.log(`Updated manifest: ${MANIFEST_PATH} (${manifestList.length} materials)`);

  // Update data/catalog.js
  const catalogJsContent = `/**
 * LinguaStudio - Externalized Default Catalog
 * Auto-generated by scripts/sync-catalog.js
 * Last synced: ${new Date().toISOString()}
 */
window.DEFAULT_CATALOG = ${JSON.stringify(materials, null, 2)};
`;

  fs.writeFileSync(CATALOG_BUNDLE_PATH, catalogJsContent, 'utf-8');
  console.log(`Updated catalog bundle: ${CATALOG_BUNDLE_PATH}`);
  console.log(`Successfully synced ${materials.length} material(s).`);
}

syncCatalog();
