#!/usr/bin/env python3
"""
sync-catalog.py
Scans data/materials/*.json, updates data/materials/manifest.json and bundles into data/catalog.js.
Usage: python3 scripts/sync-catalog.py
"""

import os
import json
from datetime import datetime

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MATERIALS_DIR = os.path.join(ROOT_DIR, "data", "materials")
MANIFEST_PATH = os.path.join(MATERIALS_DIR, "manifest.json")
CATALOG_BUNDLE_PATH = os.path.join(ROOT_DIR, "data", "catalog.js")

def sync_catalog():
    if not os.path.exists(MATERIALS_DIR):
        print(f"Error: Materials directory not found: {MATERIALS_DIR}")
        return

    files = sorted([f for f in os.listdir(MATERIALS_DIR) if f.endswith(".json") and f != "manifest.json"])
    materials = []
    manifest_list = []

    for file in files:
        file_path = os.path.join(MATERIALS_DIR, file)
        try:
            with open(file_path, "r", encoding="utf-8") as f:
                item = json.load(f)
            
            if not item.get("id") or not item.get("chinese") or not item.get("english"):
                print(f"[WARN] Skipping {file}: Missing required fields ('id', 'chinese', or 'english')")
                continue

            materials.append(item)
            manifest_list.append(file)
        except Exception as e:
            print(f"[ERROR] Failed to parse {file}: {e}")

    with open(MANIFEST_PATH, "w", encoding="utf-8") as f:
        json.dump(manifest_list, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print(f"Updated manifest: {MANIFEST_PATH} ({len(manifest_list)} materials)")

    catalog_js = f"""/**
 * LinguaStudio - Externalized Default Catalog
 * Auto-generated by scripts/sync-catalog.py
 * Last synced: {datetime.utcnow().isoformat()}Z
 */
window.DEFAULT_CATALOG = {json.dumps(materials, ensure_ascii=False, indent=2)};
"""
    with open(CATALOG_BUNDLE_PATH, "w", encoding="utf-8") as f:
        f.write(catalog_js)
    print(f"Updated catalog bundle: {CATALOG_BUNDLE_PATH}")
    print(f"Successfully synced {len(materials)} material(s).")

if __name__ == "__main__":
    sync_catalog()
